SELECT NOME, FUN.NUMERO_DEPARTAMENTO FROM FUN WHERE NUMERO_DEPARTAMENTO= 20 UNION ALL SELECT '-------------', NULL FROM TABELA1 UNIAO ALL SELECT NOME, NUMERO_DEPARTAMETNO FROM AREA;

SELECT NUMERO_DEPARTAMENTO FROM FUN UNION SELECT NUMERO_DEPARTAMENTO FROM AREA;

SELECT f.NOME, a.CIDADE FROM FUN f, AREA a WHERE F.NUMERO_DEPARTAMENTO = a.NUMERO_DEPARTAMENTO AND F.NUMERO_DEPARTAMENTO = 20;

SELECT f.NOME, a.CIDADE, f.NUMERO_DEPARTAMENTO AS FUN_NUMERO_DEPARTAMENTO, A.NUMERO_DEPARTAMENTO AS AREA_NUMERO_DEPARTAMENTO FROM FUN f, AREA a WHERE f.NUMERO_DEPARTAMENTO =20;

SELECT NUMERO_DEPARTAMENTO FROM AREA WHERE NUMERO_DEPARTAMENTO NOT IN (SELECT NUMERO_DEPARTAMENTO FROM FUN);

SELECT DISTINCT NUMERO_DEPARTAMENTO FROM AREA WHERE NUMERO_DEPARTAMENTO NOT IN (SELECT NUMERO_DEPARTAMENTO FROM FUN);

SELECT F.NOME, A.CIDADE FROM FUN F, AREA A WHERE F.NUMERO_DEPARTAMENTO = 20 AND A.NUMERO_DEPARTAMENTO = F.NUMERO_DEPARTAMENTO;

SELECT NOME, COMISSAO, COALESCE(COMISSAO,0) FROM FUN WHERE COALESCE(COMISSAO,0)<(SELECT COMISSAO FROM FUN WHERE NOME = 'Daniel Pereira');

SELECT * FROM FUN;