create database teste_sql;
use teste_sql;

SELECT NUMERO_DEPARTAMENTO,NOME,SALARIO FROM FUN;

SELECT * FROM FUN WHERE NUMERO_DEPARTAMENTO = 20;

SELECT * FROM FUN WHERE (NUMERO_DEPARTAMENTO = 10 OR COMISSAO IS NOT NULL OR SALARIO <= 2000) AND NUMERO_DEPARTAMENTO = 20;

SELECT SALARIO, COMISSAO FROM FUN;

SELECT SALARIO AS GANHOS, COMISSAO AS BONUS FROM FUN;

-- consulta avançada
SELECT * FROM ( SELECT SALARIO AS GANHOS, COMISSAO AS BONUS FROM FUN) X WHERE BONUS<5000;

SELECT NOME, CARGO FROM FUN WHERE NUMERO_DEPARTAMENTO = 10;

SELECT CONCAT (NOME, ' CARGO DE ', CARGO)AS MENSAGEM FROM FUN WHERE NUMERO_DEPARTAMENTO = 20;

-- condicionais

SELECT NOME,SALARIO, CASE WHEN SALARIO <= 2000 THEN 'BAIXO' WHEN SALARIO >= 4000 THEN 'ALTO' ELSE 'MEDIO' END AS RESULTADO FROM FUN

-- limite de linhas

SELECT * FROM FUN limit 5;

SELECT NOME, CARGO FROM FUN ORDER BY RAND() LIMIT 5;

SELECT * FROM FUN WHERE COMISSAO IS NULL;

SELECT * FROM FUN WHERE COMISSAO IS NOT NULL;

SELECT COALESCE(COMISSAO,0) FROM FUN ;