create table AREA(
    NUMERO_DEPARTAMENTO INT PRIMARY KEY ,
    NOME VARCHAR(50),
    CIDADE VARCHAR(50)
);
INSERT INTO AREA(NUMERO_DEPARTAMENTO, NOME, CIDADE)
VALUES
    (10,'CONTABILIDADE','OSASCO'),
    (20,'PESQUISADOR','GUARULHOS'),
    (30,'VENDAS','MAUA'),
    (40,'OPERAÇÕES','DIADEMA')

INSERT INTO AREA (NUMERO_DEPARTAMENTO, NOME, CIDADE) VALUES (60,'TI','CIDADE2');

CREATE TABLE D(
    id INTEGER DEFAULT 0
);

INSERT INTO D VALUES(DEFAULT);

SELECT * FROM D;

CREATE TABLE tabela_a (id INTEGER DEFAULT 0, coluna2 VARCHAR(10));

INSERT INTO tabela_a (coluna2) VALUES ('teste');

SELECT * FROM tabela_a;

CREATE TABLE A(id INTEGER DEFAULT 0, teste VARCHAR(10));

INSERT A(id,teste) VALUES(NULL, 'TESTE');

create table AREA2 (
                      NUMERO_DEPARTAMENTO INT PRIMARY KEY,
                      NOME VARCHAR(50),
                      CIDADE VARCHAR(50)
);
INSERT INTO AREA2 (NUMERO_DEPARTAMENTO, NOME, CIDADE) SELECT NUMERO_DEPARTAMENTO,NOME,CIDADE FROM AREA;

SELECT NUMERO_DEPARTAMENTO,NOME, SALARIO FROM FUN;

SELECT NUMERO_DEPARTAMENTO,NOME, SALARIO FROM FUN WHERE NUMERO_DEPARTAMENTO = 20 ORDER BY 1,3;

UPDATE FUN SET SALARIO = SALARIO * 1.20 WHERE NUMERO_DEPARTAMENTO = 20;

SELECT NUMERO_DEPARTAMENTO,NOME,SALARIO AS SALARIO_INICIAL, SALARIO*.10 AS VALOR_SOMADO, SALARIO *1.10 AS SALARIO_REAJUSTADO FROM FUN WHERE NUMERO_DEPARTAMENTO =20;

CREATE TABLE FUN_2 AS SELECT * FROM FUN;

SELECT *FROM FUN_2;

UPDATE FUN SET SALARIO = SALARIO *1.30 WHERE ID  IN (SELECT ID FROM FUN_2);

SELECT MIN(ID),NOME FROM FUN GROUP BY NOME;