select NUMERO_DEPARTAMENTO, avg(SALARIO) as media_salarial from FUN group by NUMERO_DEPARTAMENTO;

select FUN.NUMERO_DEPARTAMENTO,min(SALARIO) as Salario_minimo, max(SALARIO) as Salario_maximo From FUN group by NUMERO_DEPARTAMENTO;

select sum(FUN.SALARIO) from FUN;

select sum(FUN.COMISSAO) FROM FUN;

SELECT FUN.NUMERO_DEPARTAMENTO, SUM(FUN.COMISSAO) FROM FUN WHERE NUMERO_DEPARTAMENTO IN (10,20,30) GROUP BY FUN.NUMERO_DEPARTAMENTO;

-- CONTAGEM DE LINHAS EM UMA TABELA

SELECT  COUNT(*) FROM FUN;

SELECT NUMERO_DEPARTAMENTO, COUNT(*) FROM FUN GROUP BY NUMERO_DEPARTAMENTO ;

SELECT FUN.NUMERO_DEPARTAMENTO,FUN.COMISSAO FROM FUN;

SELECT NOME,SALARIO, SUM(SALARIO) OVER (ORDER BY SALARIO, ID) AS TOTAL FROM FUN ORDER BY  2;

SELECT SALARIO FROM FUN WHERE NUMERO_DEPARTAMENTO = 20 ORDER BY SALARIO;

SELECT SALARIO from ( select SALARIO, dense_rank()over( order by MODA desc) as RANK from ( select SALARIO, count(*) as MODA from FUN where NUMERO_DEPARTAMENTO = 20 group by SALARIO ) x ) y where RANK = 1;

SELECT (SUM(CASE WHEN FUN.NUMERO_DEPARTAMENTO= 20 THEN SALARIO END)/SUM(SALARIO) ) *100 AS PORCENTAGEM FROM FUN;

SELECT AVG(COALESCE(COMISSAO,0)) AS MEDIA_COMISSAO FROM FUN WHERE NUMERO_DEPARTAMENTO = 20;

SELECT NOME, FUN.COMISSAO FROM FUN WHERE NUMERO_DEPARTAMENTO = 20 ORDER BY COMISSAO DESC;

SELECT (SUM(SALARIO)-MIN(SALARIO)-MAX(SALARIO))/(COUNT(*)-2) AS MEDIA_TRUNCADA FROM FUN;

SELECT AVG(SALARIO) FROM FUN WHERE SALARIO NOT IN ((SELECT MIN(SALARIO) FROM FUN ), (SELECT MAX(SALARIO) FROM FUN));