USE teste_sql;

SELECT NOME, CARGO, SALARIO FROM FUN WHERE NUMERO_DEPARTAMENTO=20 order by SALARIO desc;

SELECT NOME, CARGO, SALARIO FROM FUN WHERE NUMERO_DEPARTAMENTO=20 order by 3;
-- ordendo assim quer diser que sera a 3 coluna ou seja como especificou salario como 3 coluna, é ela

SELECT  NUMERO_DEPARTAMENTO, ID,SALARIO,NOME,CARGO FROM FUN ORDER BY  NUMERO_DEPARTAMENTO;

SELECT NOME,SALARIO,COMISSAO FROM (SELECT NOME,SALARIO,COMISSAO, CASE WHEN COMISSAO IS NULL THEN 0 ELSE 1 END AS IS_NULL FROM FUN) X ORDER BY IS_NULL DESC, COMISSAO;

